name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        emacs_version:
          # - 24.1
          # - 24.2
          # - 24.3
          # - 24.4
          # - 24.5
          # - 25.1
          # - 25.2
          # - 25.3
          #- 26.1
          #- 26.2
          #- 26.3
          - 27.1
          # - snapshot
        python_version:
          #- 3.5
          #- 3.6
          #- 3.7
          - 3.8
    steps:
    # Checkout
    - uses: actions/checkout@v2
    # Emacs
    - name: Set up Emacs ${{ matrix.emacs_version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    # Cask
    - name: Set up Cask
      uses: conao3/setup-cask@master
      with:
          version: 'snapshot'
     # Python
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version : ${{ matrix.python_version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml
    - name: Run Emacs tests
      run: |
        emacs --version
        make test
